# Generated by Django 5.0.1 on 2024-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_billionaireswishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi', models.CharField(blank=True, max_length=255, null=True)),
                ('days', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
