# Generated by Django 5.0.1 on 2024-01-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_businessdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessdata',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
